# This is the configuration file for your local development environment. By
# default, it runs a single server on port 8080. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.
#
# When running your server locally, the server ports are the same as the public
# facing ports.

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: 10.100.16.220
  publicPort: 28080
  publicScheme: http

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: 10.100.16.220
  publicPort: 28081
  publicScheme: http

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: 10.100.16.220
  publicPort: 28082
  publicScheme: http

# This is the database setup for your server.
database:
  host: 10.100.16.220
  port: 28090
  name: aida
  user: postgres
  requireSsl: false

# This is the setup for Redis.
redis:
  enabled: false
  host: 10.100.16.220
  port: 28091